general:
  store_waveform: true
  use_single_t_trace: false
  use_single_input_t_trace: false
  nchannels: 2
  # opt 1: ARPLS PLS, opt 2: noise-median filter
  baseline_opt: 1 
  run_type: 1
  do_max_ch: false
  threshold: 0
  trigger_ch: 2
  invert_ch: [1]
  simple_ana_ch: [-1]
  # opt 1: regular scope routine, opt 2: CAEN scan routine
  routine: 1

# user need to specify a bucket start time
# the bucket_t_end is actually the step size.
# nbuckets is the number of increment for bucket.
buckets:
  fill_bucket: false
  bucket_t_start: 23e-9
  bucket_t_end: 2.08e-9
  nbuckets: 50

# this control the fix time window search for pmax and tmax
fix_window:
  fill_fix_window: true
  fix_win_start: 23e-9
  fix_win_step_size: 2.08e-9
  fix_win_nstep: 50
  fix_win_edge_dist: 0